import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir, readFile, writeFile} from 'node:fs/promises';
const base = process.env.STEP_URL || 'http://127.0.0.1:4173/';
const output = 'test-results';
await mkdir(output, {recursive:true});
const browser = await chromium.launch({headless:true});
const results=[];
const legacy={tag:'STEP_BACKUP_V1',app:'step',schema:1,storageKey:'step_live_v1',state:{schema:2,activeId:'legacy-task',groups:[{id:'project',name:'개인 프로젝트',collapsed:false}],tasks:[{id:'legacy-task',title:'기존 데이터 확인',type:0,prep:false,groupId:'project',memoText:'○1 원문 메모\n●A 완료 메모',startText:'원본 시작점',finishText:'백업 확인',finalized:false,pieces:[{status:'success',kind:'start',done:[true,false,false]},{status:'success',kind:'continue',done:[false,true,false]}]}]}};
try {
  for(const [name,viewport] of [['mobile',{width:390,height:844}],['desktop',{width:1440,height:1000}]]) {
    const context=await browser.newContext({viewport,acceptDownloads:true});
    const page=await context.newPage();
    const errors=[]; page.on('pageerror',error=>errors.push(error.message));
    const checkWidth=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${name}: horizontal overflow`);
    const snap=async stage=>{await checkWidth();await page.screenshot({path:`${output}/${name}-${stage}.png`,fullPage:true});};
    const by=(role,name)=>page.getByRole(role,{name,exact:true});
    await page.goto(base);
    await by('heading','어디부터 시작할까?').waitFor();
    assert.equal(await page.getByRole('textbox',{name:'비밀번호'}).count(),0);
    await snap('empty');
    await by('button','새 할 일 추가').click();
    await by('textbox','할 일 제목').fill('회로 예제 풀기');
    await by('textbox','메모').fill('○1 예제 4 확인\n이어갈 식을 남겨두기');
    await page.locator('#capture-form summary').click();
    await by('spinbutton','전체 Step').fill('2');
    await by('textbox','시작할 곳').fill('p.37 예제 4 열기');
    await by('textbox','끝 기준').fill('예제 4 풀이 확인');
    await page.locator('#capture-form').getByRole('button',{name:'추가',exact:true}).click();
    assert.equal(await page.locator('#capture-form').count(),0);
    await by('button','묶음 추가').click();
    await by('textbox','묶음 이름').fill('나중');
    await page.locator('#group-form').getByRole('button',{name:'추가',exact:true}).click();
    await by('button','회로 예제 풀기 편집').click();
    await by('textbox','제목').fill('회로 예제 이어서 풀기');
    await page.locator('#editor-form select[name="groupId"]').selectOption({label:'나중'});
    await page.locator('#editor-form summary').click();
    await by('spinbutton','전체 Step').fill('8');
    await by('button','편집 닫기').click();
    await page.reload();
    await by('button','이어서 편집').click();
    assert.equal(await by('textbox','제목').inputValue(),'회로 예제 이어서 풀기');
    await page.locator('#editor-form summary').click();
    assert.equal(await by('spinbutton','전체 Step').inputValue(),'8');
    await by('spinbutton','전체 Step').fill('2');
    await page.locator('#editor-form').getByRole('button',{name:'저장',exact:true}).click();
    await snap('list');
    const later=page.getByRole('region',{name:'나중 묶음'});
    await later.locator('.group-toggle').click();
    assert.equal(await by('button','회로 예제 이어서 풀기 편집').count(),0);
    await page.reload();
    await later.locator('.group-toggle').click();
    await by('button','회로 예제 이어서 풀기 시작·이어서').click();
    assert.equal(await page.locator('.step-position').innerText(),'1/2');
    const first=page.locator('[data-action="small-check"][data-index="0"]');
    await first.click(); assert.equal(await first.getAttribute('aria-pressed'),'true');
    const checkedContrast = await first.evaluate(el => {
      const luminance = color => {const rgb = color.match(/[\d.]+/g).slice(0,3).map(Number).map(v => v/255).map(v => v <= .04045 ? v/12.92 : ((v+.055)/1.055)**2.4); return rgb.reduce((n,v,i) => n + v*[.2126,.7152,.0722][i],0);};
      const style = getComputedStyle(el), text = luminance(style.color), background = luminance(style.backgroundColor);
      return (Math.max(text,background)+.05)/(Math.min(text,background)+.05);
    });
    assert.ok(checkedContrast >= 4.5, `completed action contrast: ${checkedContrast}`);
    await first.click(); assert.equal(await first.getAttribute('aria-pressed'),'false');
    await first.click();
    await by('button','메모 체크 1').click();
    assert.equal(await by('button','메모 체크 1').getAttribute('aria-pressed'),'true');
    await page.locator('.timer-panel summary').click();
    await by('button','타이머 시작').click();
    await by('button','잠깐 중단').click();
    await by('textbox','이어서 할 곳 (선택)').fill('두 번째 식부터 다시 보기');
    await page.locator('#note-form').getByRole('button',{name:'중단하고 목록으로',exact:true}).click();
    await page.reload();
    await by('button','이어서').click();
    assert.equal(await page.locator('.step-position').innerText(),'1/2');
    assert.equal(await first.getAttribute('aria-pressed'),'true');
    assert.ok((await page.locator('.resume-note').innerText()).includes('두 번째 식부터 다시 보기'));
    await snap('focus');
    await by('button','이번 Step 마침').click();
    assert.equal(await page.locator('.step-position').innerText(),'2/2');
    assert.equal(await by('button','완료').count(),0);
    await first.click();
    await page.waitForTimeout(500); // The deliberate guard prevents a double tap from processing two Steps.
    await by('button','이번 Step 마침').click();
    await by('button','완료').waitFor();
    assert.equal(await page.locator('[data-action="small-check"][aria-pressed="true"]').count(),1);
    assert.equal(await page.locator('[data-action="small-check"][aria-pressed="false"]').count(),2);
    await snap('ready');
    await page.waitForTimeout(500);
    await by('button','완료').click();
    await by('heading','하나, 해냈어요.').waitFor();
    for(const label of ['새 할 일','보관함에 두기','끝낸 일로 치우기','삭제']) assert.equal(await by('button',label).isVisible(),true);
    await snap('completed');
    await by('button','보관함에 두기').click();
    await by('button','회로 예제 이어서 풀기 완료 내용 보기').click();
    await by('button','끝낸 일로 치우기').click();
    await page.locator('[data-action="show-shelf"]').click();
    await by('button','회로 예제 이어서 풀기 편집').click();
    await by('button','보관함으로 꺼내기').click();
    await by('button','회로 예제 이어서 풀기 편집').waitFor();
    await by('button','나중 묶음 편집').click();
    await by('button','묶음 삭제').click();
    await by('button','옮기고 묶음 삭제').click();
    assert.equal(await page.getByRole('region',{name:'나중 묶음'}).count(),0);
    await by('button','회로 예제 이어서 풀기 편집').waitFor();
    await by('button','백업·복구와 도움말').click();
    await page.locator('#backup-file').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});
    await by('button','이 백업으로 복원').click();
    await by('button','복원').click();
    await by('heading','기존 데이터 확인').waitFor();
    await by('button','완료').waitFor();
    await page.reload();
    assert.equal(await page.locator('.step-position').innerText(),'2/2');
    assert.equal(await page.locator('[data-action="small-check"][aria-pressed="true"]').count(),1);
    await by('button','아직 남았어요 · Step 추가').click();
    assert.equal(await page.locator('.step-position').innerText(),'3/3');
    await by('button','막혔어요').click();
    await by('textbox','이어서 할 곳 (선택)').fill('도움 될 예제 하나 찾아보기');
    await by('button','작은 Step으로 다시 시작').click();
    assert.equal(await page.locator('.step-position').innerText(),'4/4');
    assert.ok((await page.locator('[data-action="small-check"]').first().innerText()).includes('도움 될 예제 하나 찾아보기'));
    await by('button','백업·복구와 도움말').click();
    const downloaded=page.waitForEvent('download');
    await by('button','백업 내려받기').click();
    const file=await downloaded; const data=JSON.parse(await readFile(await file.path(),'utf8'));
    assert.equal(data.state.tasks[0].id,'legacy-task');
    assert.equal(data.state.tasks[0].pieces.length,4);
    assert.equal(data.state.tasks[0].pieces[2].status,'blocked');
    assert.deepEqual(data.state.tasks[0].pieces[1].done,[false,true,false]);
    assert.deepEqual(errors,[]);
    results.push({viewport:name,status:'passed',flows:['create','persistent-edit-draft','groups','checks-and-undo','memo-token','pause-reload-resume','step-complete','explicit-final','keep-shelf-restore','group-delete-keeps-tasks','legacy-import','extend','blocked','backup-export']});
    await context.close();
  }
} catch(error) {
  await writeFile(`${output}/result.json`,JSON.stringify({results,error:error.stack},null,2));
  throw error;
} finally {await browser.close();}
await writeFile(`${output}/result.json`,JSON.stringify({results},null,2));
console.log(JSON.stringify({results},null,2));
