import { chromium } from 'playwright';

const url=process.env.STEP_URL||'http://127.0.0.1:4174/';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.route('https://www.gstatic.com/**',route=>route.abort());
await page.goto(url,{waitUntil:'domcontentloaded'});
await page.waitForFunction(()=>document.documentElement.dataset.stepCoreLoaded==='true',null,{timeout:20000});
await page.evaluate(()=>{
  document.body.classList.remove('sync-locked');
  document.getElementById('syncGate').hidden=true;
  state=baseState();
  saveState('experience-test-start');
  renderAll();
});
if(!await page.locator('#sx .sx-list').count())throw new Error('Default list did not render');
await page.locator('#topBtn').click();
await page.locator('#sx-new-title').fill('회로 과제');
await page.locator('#sx-new-memo').fill('3번 중간부터 이어서');
await page.locator('#sx-capture-form button[type=submit]').click();
if(await page.locator('#sx-capture-form').count())throw new Error('Capture did not close after add');
let result=await page.evaluate(()=>({count:state.tasks.length,active:state.activeId,group:state.tasks[0]?.groupId,notes:state.tasks[0]?.memoText}));
if(result.count!==1||result.active||!result.group||result.notes!=='3번 중간부터 이어서')throw new Error(`Capture state: ${JSON.stringify(result)}`);
const id=await page.evaluate(()=>state.tasks[0].id);
await page.locator(`#sx .sx-row-main[data-id="${id}"]`).click();
await page.locator('#sx-edit-group').selectOption('later');
await page.locator('#sx-edit-form button[type=submit]').click();
if(await page.evaluate(()=>state.tasks[0].groupId)!=='later')throw new Error('Group transfer failed');
await page.locator('#sx [data-action="group-toggle"][data-id="later"]').click();
await page.locator('#sx [data-action="group-edit"][data-id="later"]').click();
await page.locator('#sx-group-title').fill('이번 주');
await page.locator('#sx-group-form button[type=submit]').click();
if(!await page.getByRole('button',{name:/이번 주/}).count())throw new Error('Group rename missing');
await page.locator(`#sx [data-action="activate"][data-id="${id}"]`).click();
if(!await page.locator('#sx .sx-execution').count())throw new Error('Execution did not open');
if((await page.locator('#sx .sx-progress-caption').innerText()).trim()!=='1 / 1')throw new Error('Inconsistent Step position');
if(await page.locator('#sx .sx-action').count()!==3)throw new Error('1/2/3 actions missing');
await page.locator('#sx .sx-action[data-index="0"]').click();
if(!await page.locator('#sx .sx-action[data-index="0"]').evaluate(el=>el.classList.contains('sx-done')))throw new Error('Checked action not dimmed');
if(!await page.locator('#sx .sx-action[data-index="1"]').evaluate(el=>el.classList.contains('sx-next')))throw new Error('Next action not emphasized');
const hold=async(kind)=>{
  const button=page.locator(`#sx button[data-hold="${kind}"]`);
  await button.scrollIntoViewIfNeeded();
  const box=await button.boundingBox();
  if(!box)throw new Error(`Hold button not visible: ${kind}`);
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
  await page.mouse.down();
  await page.waitForTimeout(1250);
  await page.mouse.up();
  await page.waitForTimeout(650);
};
await hold('success');
if(!await page.locator('#sx button[data-hold="final"]').count())throw new Error('Last Step did not reach explicit closure');
if(await page.evaluate(()=>state.tasks[0].finalized))throw new Error('Finalized before explicit task completion');
await hold('final');
if(!await page.locator('#sx [data-action="putaway"]').count())throw new Error('Post-completion choices absent');
if(!await page.evaluate(()=>state.tasks[0].finalized))throw new Error('Explicit task completion failed');
await page.locator('#sx .sx-complete-actions [data-action="putaway"]').click();
if(!await page.locator('#sx .sx-row.sx-done .sx-row-main').count())throw new Error('Finished row not dimmed');
await page.reload({waitUntil:'domcontentloaded'});
await page.waitForFunction(()=>document.documentElement.dataset.stepCoreLoaded==='true',null,{timeout:20000});
result=await page.evaluate(()=>({task:state.tasks.find(t=>t.title==='회로 과제'),groups:state.groups,cloud:window.StepSyncApp.getCloudState()}));
if(!result.task?.finalized||result.task?.groupId!=='later'||!result.groups.some(g=>g.id==='later'&&g.name==='이번 주'))throw new Error(`State lost after reload: ${JSON.stringify(result)}`);
if(!result.cloud.tasks.some(t=>t.id===id&&t.groupId==='later'&&t.finalized===true)||!result.cloud.groups.some(g=>g.id==='later'&&g.name==='이번 주'))throw new Error('Groups and finalized state missing from cloud payload');
if(errors.length)throw new Error(`Browser errors: ${errors.join(' | ')}`);
await page.screenshot({path:'/tmp/step-experience-mobile.png',fullPage:true});
await page.setViewportSize({width:1280,height:800});
await page.evaluate(()=>{document.body.classList.remove('sync-locked');document.getElementById('syncGate').hidden=true;renderAll();});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);
if(overflow)throw new Error('Horizontal overflow on desktop');
await page.screenshot({path:'/tmp/step-experience-desktop.png',fullPage:true});
await browser.close();
