function renderTaskListStable(){var y=window.scrollY;renderTaskList();requestAnimationFrame(function(){window.scrollTo(0,y)})}
    function toggleLibraryTask(taskId){taskId=String(taskId);armedDeleteId=null;state.selectedLibraryId=state.selectedLibraryId===taskId?null:taskId;saveState();renderTaskListStable()}
    function renderTaskList(){
      var tasks=storedTasks(),shelf=doneShelfTasks();
      if(!tasks.length&&!shelf.length){state.selectedLibraryId=null;el.listCard.style.display="none";el.listCard.innerHTML="";return}
      var visible=tasks.concat(state.doneShelfOpen?shelf:[]);
      if(state.selectedLibraryId&&!findTaskInList(state.selectedLibraryId,visible))state.selectedLibraryId=null;
      el.listCard.style.display="block";
      el.listCard.innerHTML='<button class="library-toggle" id="libraryToggle"><span><strong>할 일 보관함</strong> '+tasks.length+'개</span><span class="chev">'+(state.libraryOpen?'⌄':'〉')+'</span></button>'+(state.libraryOpen?'<div class="tasks">'+tasks.map(renderTaskButton).join("")+renderDoneShelfSection(shelf)+'</div>':'');
      var toggle=byId("libraryToggle");if(toggle)toggle.onclick=function(){state.libraryOpen=!state.libraryOpen;state.selectedLibraryId=null;saveState();renderTaskList()};
      var shelfToggle=byId("doneShelfToggle");if(shelfToggle)shelfToggle.onclick=function(){armedDeleteId=null;state.doneShelfOpen=!state.doneShelfOpen;if(!state.doneShelfOpen&&state.selectedLibraryId&&findTaskInList(state.selectedLibraryId,shelf))state.selectedLibraryId=null;saveState();renderTaskListStable()};
      all(".task",el.listCard).forEach(function(card){card.onclick=function(event){if(event.target&&event.target.closest&&event.target.closest("button"))return;toggleLibraryTask(card.dataset.id)};card.onkeydown=function(event){if(event.key!=="Enter"&&event.key!==" ")return;if(event.target&&event.target.closest&&event.target.closest("button"))return;event.preventDefault();toggleLibraryTask(card.dataset.id)}});
      all("[data-resume-id]",el.listCard).forEach(function(btn){btn.onclick=function(event){event.stopPropagation();selectTask(btn.dataset.resumeId)}});
      all("[data-shelf-id]",el.listCard).forEach(function(btn){btn.onclick=function(event){event.stopPropagation();moveTaskToDoneShelf(btn.dataset.shelfId)}});
      all("[data-unshelf-id]",el.listCard).forEach(function(btn){btn.onclick=function(event){event.stopPropagation();restoreTaskFromDoneShelf(btn.dataset.unshelfId)}});
      all("[data-delete-shelf-id]",el.listCard).forEach(function(btn){btn.onclick=function(event){event.stopPropagation();deleteDoneShelfTask(btn.dataset.deleteShelfId)}});
    }
    function renderTaskButton(task){var done=isTaskDone(task),note=cleanMemo(task.memoText),selected=state.selectedLibraryId===task.id,right="";if(selected){right='<div class="task-card-actions">'+(done?'<button class="shelf-action" data-shelf-id="'+attr(task.id)+'">치우기</button>':'')+'<button class="task-resume" data-resume-id="'+attr(task.id)+'">이어서 하기 →</button></div>'}else if(done){right='<div class="task-meta">완료</div>'}var cls="task "+(done?"done ":"")+(selected?"selected":"");return'<div class="'+cls+'" data-id="'+attr(task.id)+'" role="button" tabindex="0" aria-label="'+attr(task.title)+'"><div class="task-top"><div class="task-title">'+typeBadge(task)+'<div class="task-name">'+safe(task.title)+'</div></div>'+right+'</div>'+(note?'<div class="task-note">'+renderMemoPreviewText(note)+'</div>':'')+renderProgressBar(task,false)+'</div>'}
    function renderDoneShelfSection(shelf){return'<button class="done-shelf-toggle" id="doneShelfToggle">'+(state.doneShelfOpen?'끝낸 일 숨기기':'끝낸 일 보기')+'</button>'+(state.doneShelfOpen?'<div class="done-shelf-panel">'+(shelf.length?shelf.map(renderDoneShelfButton).join(""):'<div class="done-shelf-empty">끝낸 일이 아직 없어요.</div>')+'</div>':'')}
    function renderDoneShelfButton(task){var note=cleanMemo(task.memoText),selected=state.selectedLibraryId===task.id,armed=armedDeleteId===task.id,cls="task done shelved "+(selected?"selected":""),actions='<div class="task-card-actions"><button class="shelf-action" data-unshelf-id="'+attr(task.id)+'">꺼내기</button><button class="shelf-action danger '+(armed?'armed':'')+'" data-delete-shelf-id="'+attr(task.id)+'">'+(armed?'🗑 삭제 확인':'🗑 삭제')+'</button></div>';return'<div class="'+cls+'" data-id="'+attr(task.id)+'" role="button" tabindex="0" aria-label="'+attr(task.title)+'"><div class="task-top"><div class="task-title">'+typeBadge(task)+'<div class="task-name">'+safe(task.title)+'</div></div>'+actions+'</div>'+(note?'<div class="task-note">'+renderMemoPreviewText(note)+'</div>':'')+renderProgressBar(task,false)+'</div>'}
